# Generated by Django 5.2 on 2025-04-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_timeslot"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("date", "start_time", "end_time")},
        ),
    ]
