# Generated by Django 5.2 on 2025-04-21 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("concluída", "Concluída"),
                ],
                default="confirmada",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReservationGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest", models.CharField(max_length=500)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="core.reservation",
                    ),
                ),
            ],
        ),
    ]
