# Generated by Django 5.2 on 2025-04-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_reservation_status_reservationguest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("space", "time_slot"),
                name="unique_space_time_slot",
                violation_error_message="Este espaço já está reservado neste horário.",
            ),
        ),
    ]
