# Generated by Django 5.2.1 on 2025-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
