# Generated by Django 5.2.1 on 2025-05-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_category_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
