# Generated by Django 5.2.1 on 2025-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
