# Generated by Django 5.2.1 on 2025-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_space_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
