# Generated by Django 5.2.1 on 2025-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_timeslot_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("confirmada", "Confirmada"), ("concluída", "Concluída")],
                default="Confirmada",
                max_length=20,
            ),
        ),
    ]
